on:
    push:
      branches:
        - main
  
jobs:
    e2e-tests:
      runs-on: windows-latest
  
      steps:
        - uses: actions/checkout@v2
  
        - uses: actions/setup-node@v2
          with:
            node-version: '^20.10.6'
  
        - uses: microsoft/playwright-github-action@v1
  
        - name: Install dependencies
          run: npm install
  
        - name: Install Playwright Browsers
          run: npx playwright install
  
        - name: Run Playwright Tests
          run: npx playwright test