on:
    push:
      branches:
        - main
        - master
  
jobs:
    e2e-tests:
      runs-on: windows-latest
  
      steps:
        - uses: actions/checkout@v2
  
        - uses: actions/setup-node@v2
          with:
            node-version: '20.10.6'
  
        - uses: microsoft/playwright-github-action@v1
  
        - name: Install dependencies and run tests
          run: npm install && npm test